### ISSUE TITLE
Improvement Request: Use Lighthouse extension for Google Chrome to identify areas of improvement

### ISSUE THREAD

**Issue by vicmaster** [magma-labs/til#43]
### Feature Description

The feature would involve using the Lighthouse extension for Google Chrome to identify areas of improvement in the app's performance and implement solutions to address any issues.

### Benefit

This feature would help to improve the overall performance and user experience of the app by identifying and addressing any issues that may be impacting its performance. It would also allow the engineering team to prioritize and focus on the most impactful improvements.

### Use Cases

* The engineering team can use the Lighthouse extension to analyze the app's performance and identify areas for improvement.
* The engineering team can implement solutions to address any issues identified by the Lighthouse extension.

Implementation

To implement this feature, the following steps would be necessary:

* Install the Lighthouse extension for Google Chrome.
* Use the extension to analyze the app's performance and identify any issues.
* Use the results of the analysis to prioritize and plan improvements to the app.
* Implement solutions to address the identified issues.

### Additional Notes

It may be necessary to update the app's codebase or infrastructure to implement the necessary improvements. It may also be useful to periodically re-run the Lighthouse analysis to ensure that the app's performance remains optimized.

**Comment by aldompe95** [comment]
I think its safe to close this now @vicmaster
